name: CI

on:
  push:
  pull_request:

jobs:
  linux-build-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake --preset debug
      - name: Build
        run: cmake --build --preset debug -j2
      - name: Test
        run: ctest --preset debug --output-on-failure

